name: gitconfig

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ms-newton-1
    steps:
      - name: Checkout test-actions
        uses: actions/checkout@v2
      - name: Test
        run: |
          set -x
          export BTI_DEVELOPER_EMAIL
          BTI_DEVELOPER_EMAIL=$(git config --global --get user.email)
          echo $? 2>&1
          echo "BTI_DEVELOPER_EMAIL is $BTI_DEVELOPER_EMAIL" 2>&1
