name: github-context

on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: '🧪 Dry run'
        type: boolean
        default: false
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_REF" 2>&1
          echo "$GITHUB_CONTEXT" 2>&1
          echo "dry_run: ${{ github.event.inputs.dry_run }}" 2>&1
