name: large

on:
  workflow_dispatch:

env:
  USER: ${{ github.actor }}

jobs:
  build:
    runs-on: ubuntu-latest-4-cores
    steps:
      - name: Checkout test-actions
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.ONSHAPE_REPO_PAT }}
      - name: Hello
        run: |
          set -x
          df -h 2>&1
          lsb_release -a 2>&1
