name: mactest1

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: mactest1
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_REF"
          echo "$GITHUB_CONTEXT"
