name: monrest

on:
  workflow_dispatch:

jobs:
  build-2204:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout test-actions
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.ONSHAPE_REPO_PAT }}
      - name: build-2204
        run: |
          set -x
          lsb_release -a 2>&1
          type mongo 2>&1
          mongo --version 2>&1
          type mongorestore 2>&1
  build-2004:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout test-actions
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.ONSHAPE_REPO_PAT }}
      - name: build-2004
        run: |
          set -x
          lsb_release -a 2>&1
          type mongo 2>&1
          mongo --version 2>&1
          type mongorestore 2>&1
