name: querysecret

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout test-actions
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.ONSHAPE_REPO_PAT }}
      - name: Hello
        env:
          BUILDMASTER_SSH_KEY: ${{ secrets.BUILDMASTER_SSH_KEY }}
          RETRIEVAL_PUBLISH_AWS_SECRET_ACCESS_KEY: ${{ secrets.RETRIEVAL_PUBLISH_AWS_SECRET_ACCESS_KEY }}
        run: |
          set -x
          echo "$BUILDMASTER_SSH_KEY" > BUILDMASTER_SSH_KEY.txt
          echo "$RETRIEVAL_PUBLISH_AWS_SECRET_ACCESS_KEY" > RETRIEVAL_PUBLISH_AWS_SECRET_ACCESS_KEY.txt
      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: |
            BUILDMASTER_SSH_KEY.txt
            RETRIEVAL_PUBLISH_AWS_SECRET_ACCESS_KEY.txt
