---

name: schedule-jirasync

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
#  schedule:
#    - cron: "*/5 * * * *"

jobs:
  trigger-build:
    name: Schedule
    runs-on: ubuntu-latest
    steps:
      - id: workflow-info
        uses: onshape/actions-workflow-info@v7
        with:
          name: jirasync
          branch: ${{ github.ref_name }}
          repository: ${{ github.repository }}
          token: ${{ secrets.ONSHAPE_REPO_PAT }}
      - name: Display info
        run: |
          echo "running-jobs-count=${{ steps.workflow-info.outputs.running-jobs-count }}"
      - name: Run
        if: ${{ steps.workflow-info.outputs.running-jobs-count == '0' }}
        uses: onshape/actions-workflow-dispatch@v1.1
        with:
          workflow: jirasync
          token: ${{ secrets.ONSHAPE_REPO_PAT }}
