name: summary

on:
  workflow_dispatch:

env:
  USER: ${{ github.actor }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout test-actions
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.ONSHAPE_REPO_PAT }}
      - name: Hello
        run: |
          ./summary.bash
