name: tailor

on:
  workflow_dispatch:

env:
  USER: ${{ github.actor }}

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout test-actions
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.ONSHAPE_REPO_PAT }}
      - name: Test
        run: |
          set -x
          echo "JAVA_HOME is $JAVA_HOME"
          printf "\n------------------\n\n" 2>&1
          df -m 2>&1
          printf "\n------------------\n\n" 2>&1
          docker image ls 2>&1
          #dpkg-query --show --showformat='${Installed-Size}\t${Package}\n' | sort -rh | head -50 | awk '{print $1/1024, $2}' 2>&1
          #dpkg-query --show --showformat='${Installed-Size}\t${Package}\n' | sort -rh > /tmp/jj
          #cat /tmp/jj
          docker info
          df -m /var/lib/docker 2>&1
          sudo du -sh /var/lib/docker 2>&1
          printf "\n================================================================================\n\n" 2>&1
          docker rmi $(docker images --filter=reference="node:*" -q) 2>&1
          sudo du -sh /var/lib/docker 2>&1
          docker system prune -a -f
          #sudo apt-get purge azure-cli google-cloud-sdk microsoft-edge-stable google-chrome-stable 2>&1
          printf "\n------------------\n\n" 2>&1
          df -m 2>&1
