name: test-dyndbput

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Set expires
        id: expires
        run: |
          twelveMonsInSecs=$((12 * 31 * 24 * 60 * 60))
          expires=$(( $(date +%s) + $twelveMonsInSecs ))
          echo "::set-output name=value::${expires}"
      - name: Put DynamoDB Item
        uses: onshape/actions-dynamodb-actions@v1.2.1
        env:
          AWS_DEFAULT_REGION: us-west-2
          AWS_REGION: us-west-2
          AWS_ACCESS_KEY_ID: ${{ secrets.ONSHAPE_CI_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.ONSHAPE_CI_AWS_SECRET_ACCESS_KEY }}
        with:
          operation: put
          region: us-west-2
          table: actions-lsb
          item: |
            {
              "repo": "ios",
              "workflowBranch": "ios-test-demo-c/rel-1.123",
              "lsb": "deadbeef",
              "expires": ${{ steps.expires.outputs.value }}
            }
