---

name: update-std-cad

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:

jobs:
  Message:
    runs-on: ubuntu-latest
    steps:
      - name: Run
        run: |
          {
           echo -e "This workflow has moved to:\n"
           echo "https://github.com/onshape/newton/actions/workflows/${{ github.workflow }}.yml"
          } > $GITHUB_STEP_SUMMARY
